export const DB_CONNECTION_NAME = 'mongo'
export const WAITING_TO_RECEIVE = 'waiting-to-receive'
export const IN_DESTINATION = 'in-destination' // สินค้าถึงปลายทาง (ไทย)
export const CREATED = 'created' // สร้าง
export const REGISTERED = 'registered' // ลงทะเบียน
export const IN_TRANSIT = 'in-transit' // อยู่ระหว่างการขนส่ง
export const DELIVERED = 'delivered' // จัดส่งแล้ว
export const SIGN_UP = 'sign-up'
export const FORGOT_PASSWORD = 'forgot-password'
export const TH_PHONE_CODE = '+66'
export const PHONE_CODES = [TH_PHONE_CODE]
export const ACTIVE = 'active'
export const INACTIVE = 'inactive'
export const USER_STATUS = [ACTIVE, INACTIVE]
export const USER = 'user'
export const DEALER = 'dealer'
export const ADMIN = 'admin'
export const SYSTEM = 'system'
export const USER_ROLES = [USER, ADMIN, SYSTEM]
export const USER_LEVEL = [USER, DEALER]
export const LOCAL = 'local'
export const STRATEGIES = [LOCAL]
export const NOT_AUTHORIZED = 'not authorized'
export const NO_CONTENT = 'no content'
export const BAD_REQUEST = 'bad request'
export const INTERNAL_ERROR = 'internal error'
export const SUCCESS = 'success'
export const USER_NOT_ALLOW = 'user is not allow'
export const REQUIRE_JWT = 'require jwt'
export const OUT_OF_SCOPE = 'out of scope'
export const INVALID_TOKEN = 'invalid token'
export const BEARER = 'Bearer'
export const JWT = 'JWT'
export const ACCESS_TOKEN = 'accessToken'
export const REFRESH_TOKEN = 'refreshToken'
export const KILOGRAM = 'kilogram'
export const PIECE = 'piece'
export const TH = 'th'
export const JP = 'jp'
